#pragma checksum "C:\Users\SHREE\source\repos\Sample\Pages\Accordians.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "a66fa9921c6025131c4a170a960c4b4812620078"
// <auto-generated/>
#pragma warning disable 1591
namespace Sample.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Sample;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "C:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Sample.Shared;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/Accordians")]
    public partial class Accordians : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h1>Here are some cool accordians</h1>\r\n\r\n");
            __builder.AddMarkupContent(1, "<p>This component demonstrates fetching data from the server.</p>\r\n");
            __builder.OpenElement(2, "img");
            __builder.AddAttribute(3, "src", 
#nullable restore
#line 7 "C:\Users\SHREE\source\repos\Sample\Pages\Accordians.razor"
           imageURL1

#line default
#line hidden
#nullable disable
            );
            __builder.AddAttribute(4, "width", "500");
            __builder.CloseElement();
            __builder.AddMarkupContent(5, "\r\n");
            __builder.OpenElement(6, "input");
            __builder.AddAttribute(7, "id", "Button1");
            __builder.AddAttribute(8, "type", "button");
            __builder.AddAttribute(9, "value", "Click to show more stuff");
            __builder.AddAttribute(10, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 8 "C:\Users\SHREE\source\repos\Sample\Pages\Accordians.razor"
                                                                             click

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseElement();
            __builder.AddMarkupContent(11, "\r\n");
#nullable restore
#line 9 "C:\Users\SHREE\source\repos\Sample\Pages\Accordians.razor"
 if (show == true)
{

#line default
#line hidden
#nullable disable
            __builder.AddContent(12, "    ");
            __builder.OpenComponent<Sample.Shared.Accordata>(13);
            __builder.CloseComponent();
            __builder.AddMarkupContent(14, "\r\n");
#nullable restore
#line 12 "C:\Users\SHREE\source\repos\Sample\Pages\Accordians.razor"

}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
#nullable restore
#line 16 "C:\Users\SHREE\source\repos\Sample\Pages\Accordians.razor"
 
    string imageURL1 = "https://images.samash.com/sa/H13/H1305XXX3-P.fpx?cvt=jpg";
    bool show = false;

    private void click(MouseEventArgs e)
    {
        show = true;
        StateHasChanged();
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
