#pragma checksum "c:\Users\SHREE\source\repos\Sample\Pages\Index.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2411aae8186ab637ff36ece5a771a4a02f77ecb1"
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace Sample.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Sample;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "c:\Users\SHREE\source\repos\Sample\_Imports.razor"
using Sample.Shared;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/")]
    public partial class Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 11 "c:\Users\SHREE\source\repos\Sample\Pages\Index.razor"
 

    string xyz = "Tarushv";
    int count = 100;

    protected override void OnInitialized()
    {
        count = count * 2;
    }


#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
